# Generated by Django 4.2.21 on 2025-05-28 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed_consumption', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedconsumptionlog',
            name='objects_retrieved',
            field=models.IntegerField(default=0),
        ),
    ]
