# Generated by Django 4.2.21 on 2025-05-28 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed_consumption', '0002_feedconsumptionlog_objects_retrieved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedconsumptionlog',
            name='error_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='feedconsumptionlog',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
