# CRISP Anonymization System Configuration

# Default anonymization settings
anonymization:
  # Default anonymization level for unknown trust relationships
  default_level: "medium"
  
  # Trust level mappings to anonymization levels
  trust_mappings:
    high: "low"          # High trust = Low anonymization
    medium: "medium"     # Medium trust = Medium anonymization  
    low: "high"          # Low trust = High anonymization
    untrusted: "full"    # No trust = Full anonymization
  
  # Data type specific settings
  data_types:
    ip_address:
      enabled: true
      preserve_network_class: true  # For IPv4, preserve class A/B/C info
    
    domain:
      enabled: true
      preserve_tld_category: true   # Keep TLD categorization at high levels
      
    email:
      enabled: true
      preserve_domain_category: true
      
    url:
      enabled: true
      strip_paths: true             # Remove paths at low anonymization
  
  # Consistency settings
  hashing:
    algorithm: "md5"               # Hash algorithm for consistency
    salt: ""                       # Optional salt (leave empty for none)
    hash_length: 8                 # Length of hash in anonymized data

# Institution trust relationships
trust_relationships:
  # Example trust relationships between institutions
  # In real implementation, this would come from database
  
  default_trust: "medium"          # Default trust level for new relationships
  
  # Specific institution trust levels
  institutions:
    "university-a.edu": "high"
    "government-agency.gov": "medium" 
    "commercial-partner.com": "low"
    "unknown-institution": "untrusted"

# Processing settings
processing:
  # Bulk processing limits
  max_batch_size: 1000            # Maximum items per batch
  
  # Performance settings
  enable_caching: false           # Cache anonymized results
  cache_ttl: 3600                # Cache time-to-live in seconds
  
  # Error handling
  strict_validation: true         # Strict data format validation
  error_handling: "log"           # Options: "log", "raise", "ignore"

# Logging configuration
logging:
  level: "INFO"                   # Log level: DEBUG, INFO, WARNING, ERROR
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  
  # Log anonymization operations
  log_operations: true
  log_trust_decisions: true
  log_errors: true
  
  # File logging (optional)
  file_logging:
    enabled: false
    path: "/var/log/crisp/anonymization.log"
    max_size: "10MB"
    backup_count: 5

# Integration settings
integration:
  # STIX/TAXII integration
  stix:
    preserve_relationships: true   # Maintain indicator relationships after anonymization
    add_anonymization_metadata: true
  
  # External threat feeds
  external_feeds:
    apply_anonymization: true     # Anonymize external feed data
    default_trust_level: "low"    # Trust level for external sources
  
  # API settings
  api:
    rate_limiting: true           # Enable rate limiting
    max_requests_per_minute: 100
    require_authentication: true

# Security settings
security:
  # Audit logging
  audit:
    enabled: true
    log_data_access: true
    log_trust_changes: true
    log_configuration_changes: true
  
  # Data retention
  retention:
    log_retention_days: 90        # Keep logs for 90 days
    anonymized_data_retention: 365 # Keep anonymized data for 1 year
  
  # Access control
  access_control:
    require_authorization: true
    admin_roles: ["admin", "security_officer"]
    user_roles: ["analyst", "researcher"]

# Development and testing settings
development:
  # Testing configuration
  testing:
    use_test_data: false          # Use synthetic test data
    consistent_results: true      # Ensure consistent test results
    
  # Debug settings
  debug:
    enabled: false                # Enable debug mode
    verbose_logging: false        # Extra verbose logging
    trace_anonymization: false    # Trace anonymization steps