# Generated by Django 4.2.10 on 2025-06-25 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UserManagement", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("viewer", "Viewer"),
                    ("publisher", "Publisher"),
                    ("BlueVisionAdmin", "BlueVision Admin"),
                ],
                default="viewer",
                help_text="User's role within the organization",
                max_length=50,
            ),
        ),
    ]
