# Generated by Django 4.2.10 on 2025-06-21 15:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'institutions',
            },
        ),
        migrations.CreateModel(
            name='ThreatFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_public', models.BooleanField(default=False)),
                ('taxii_collection_id', models.CharField(blank=True, max_length=255, null=True)),
                ('taxii_server_url', models.URLField(blank=True, null=True)),
                ('taxii_api_root', models.CharField(blank=True, max_length=255, null=True)),
                ('taxii_username', models.CharField(blank=True, max_length=255, null=True)),
                ('taxii_password', models.CharField(blank=True, max_length=255, null=True)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('is_external', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_feeds', to='core.institution')),
            ],
            options={
                'db_table': 'threat_feeds',
            },
        ),
        migrations.CreateModel(
            name='TTPData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('mitre_tactic', models.CharField(blank=True, choices=[('reconnaissance', 'Reconnaissance'), ('resource_development', 'Resource Development'), ('initial_access', 'Initial Access'), ('execution', 'Execution'), ('persistence', 'Persistence'), ('privilege_escalation', 'Privilege Escalation'), ('defense_evasion', 'Defense Evasion'), ('credential_access', 'Credential Access'), ('discovery', 'Discovery'), ('lateral_movement', 'Lateral Movement'), ('collection', 'Collection'), ('command_and_control', 'Command and Control'), ('exfiltration', 'Exfiltration'), ('impact', 'Impact'), ('other', 'Other')], max_length=50, null=True)),
                ('mitre_technique_id', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stix_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('is_anonymized', models.BooleanField(default=False)),
                ('threat_feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ttp_data', to='core.threatfeed')),
            ],
            options={
                'db_table': 'ttp_data',
                'indexes': [models.Index(fields=['mitre_technique_id'], name='ttp_data_mitre_t_90a5f9_idx'), models.Index(fields=['stix_id'], name='ttp_data_stix_id_742074_idx')],
            },
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('ip', 'IP Address'), ('domain', 'Domain Name'), ('url', 'URL'), ('file_hash', 'File Hash'), ('email', 'Email Address'), ('user_agent', 'User Agent'), ('other', 'Other')], max_length=20)),
                ('value', models.TextField()),
                ('hash_type', models.CharField(blank=True, choices=[('md5', 'MD5'), ('sha1', 'SHA-1'), ('sha256', 'SHA-256'), ('other', 'Other')], max_length=10, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_seen', models.DateTimeField(blank=True, null=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('stix_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('confidence', models.IntegerField(default=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_anonymized', models.BooleanField(default=False)),
                ('original_value', models.TextField(blank=True, null=True)),
                ('threat_feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='core.threatfeed')),
            ],
            options={
                'db_table': 'indicators',
                'indexes': [models.Index(fields=['type', 'value'], name='indicators_type_514693_idx'), models.Index(fields=['stix_id'], name='indicators_stix_id_2b0296_idx')],
            },
        ),
    ]
