# Generated by Django 4.2.10 on 2025-08-15 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial_unified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="authenticationlog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="core_authentication_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="passwordresettoken",
            name="user",
            field=models.ForeignKey(
                help_text="User requesting password reset",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="core_password_reset_tokens",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="trustgroupmembership",
            name="organization",
            field=models.ForeignKey(
                help_text="Organization that is a member of this trust group",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="core_trust_group_memberships",
                to="core.organization",
            ),
        ),
        migrations.AlterField(
            model_name="trustlog",
            name="source_organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organization that initiated the action",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="core_trust_logs_as_source",
                to="core.organization",
            ),
        ),
        migrations.AlterField(
            model_name="trustlog",
            name="target_organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Target organization (if applicable)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="core_trust_logs_as_target",
                to="core.organization",
            ),
        ),
        migrations.AlterField(
            model_name="trustlog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="User who performed the action",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="core_performed_trust_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="trustrelationship",
            name="approved_by_source_user",
            field=models.ForeignKey(
                blank=True,
                help_text="User who approved on behalf of source organization",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="core_trust_approvals_as_source",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="trustrelationship",
            name="approved_by_target_user",
            field=models.ForeignKey(
                blank=True,
                help_text="User who approved on behalf of target organization",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="core_trust_approvals_as_target",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="trustrelationship",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this relationship",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="core_created_trust_relationships",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="trustrelationship",
            name="last_modified_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last modified this relationship",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="core_modified_trust_relationships",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="trustrelationship",
            name="revoked_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who revoked this relationship",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="core_revoked_trust_relationships",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="trustrelationship",
            name="source_organization",
            field=models.ForeignKey(
                help_text="Source organization in the trust relationship",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="core_trust_relationships_as_source",
                to="core.organization",
            ),
        ),
        migrations.AlterField(
            model_name="trustrelationship",
            name="target_organization",
            field=models.ForeignKey(
                help_text="Target organization in the trust relationship",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="core_trust_relationships_as_target",
                to="core.organization",
            ),
        ),
        migrations.AlterField(
            model_name="userinvitation",
            name="accepted_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who accepted the invitation",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="core_accepted_invitations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="userinvitation",
            name="inviter",
            field=models.ForeignKey(
                help_text="User who sent the invitation",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="core_sent_invitations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
