# Generated by Django 4.2.10 on 2025-08-11 10:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stixobject",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_stix_objects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="stixobject",
            name="source_organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stix_objects",
                to="core.organization",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_organizations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="networkmembership",
            name="network",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.trustnetwork"
            ),
        ),
        migrations.AddField(
            model_name="networkmembership",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.organization"
            ),
        ),
        migrations.AddField(
            model_name="institution",
            name="organization",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.organization",
            ),
        ),
        migrations.AddField(
            model_name="indicator",
            name="threat_feed",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="indicators",
                to="core.threatfeed",
            ),
        ),
        migrations.AddField(
            model_name="identity",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="identity",
            name="organization",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stix_identity",
                to="core.organization",
            ),
        ),
        migrations.AddField(
            model_name="feed",
            name="collection",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feeds",
                to="core.collection",
            ),
        ),
        migrations.AddField(
            model_name="feed",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="feed",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="publication_feeds",
                to="core.organization",
            ),
        ),
        migrations.AddField(
            model_name="feed",
            name="threat_feed",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="publication_feeds",
                to="core.threatfeed",
            ),
        ),
        migrations.AddField(
            model_name="coreuserprofile",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="core_user_profiles",
                to="core.organization",
            ),
        ),
        migrations.AddField(
            model_name="coreuserprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="core_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="collectionobject",
            name="collection",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="collection_objects",
                to="core.collection",
            ),
        ),
        migrations.AddField(
            model_name="collectionobject",
            name="stix_object",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="collection_references",
                to="core.stixobject",
            ),
        ),
        migrations.AddField(
            model_name="collection",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_collections",
                to="core.organization",
            ),
        ),
        migrations.AddField(
            model_name="collection",
            name="stix_objects",
            field=models.ManyToManyField(
                related_name="collections",
                through="core.CollectionObject",
                to="core.stixobject",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="ttpdata",
            unique_together={("mitre_technique_id", "threat_feed")},
        ),
        migrations.AlterUniqueTogether(
            name="trustrelationship",
            unique_together={("source_organization", "target_organization")},
        ),
        migrations.AddIndex(
            model_name="stixobject",
            index=models.Index(
                fields=["stix_type"], name="core_stixob_stix_ty_2dce34_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stixobject",
            index=models.Index(
                fields=["created"], name="core_stixob_created_26f121_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stixobject",
            index=models.Index(
                fields=["modified"], name="core_stixob_modifie_36f639_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stixobject",
            index=models.Index(
                fields=["created_by_ref"], name="core_stixob_created_c709a7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stixobject",
            index=models.Index(
                fields=["anonymized"], name="core_stixob_anonymi_b28775_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="networkmembership",
            unique_together={("organization", "network")},
        ),
        migrations.AlterUniqueTogether(
            name="indicator",
            unique_together={("value", "type", "threat_feed")},
        ),
        migrations.AlterUniqueTogether(
            name="feed",
            unique_together={("alias", "organization")},
        ),
        migrations.AddIndex(
            model_name="collectionobject",
            index=models.Index(
                fields=["collection", "stix_object"],
                name="core_collec_collect_e7dabc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="collectionobject",
            index=models.Index(
                fields=["date_added"], name="core_collec_date_ad_aa32cf_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="collectionobject",
            unique_together={("collection", "stix_object")},
        ),
    ]
