# Generated by Django 4.2.10 on 2025-09-17 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='indicator',
            unique_together={('value', 'type', 'threat_feed')},
        ),
        migrations.AlterField(
            model_name='indicator',
            name='stix_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='indicator',
            unique_together={('value', 'type', 'threat_feed'), ('stix_id', 'threat_feed')},
        ),
    ]
