# Generated by Django 4.2.10 on 2025-08-15 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="trustrelationship",
            options={},
        ),
        migrations.CreateModel(
            name="SystemActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("feed_added", "Feed Added"),
                            ("feed_consumed", "Feed Consumed"),
                            ("feed_deleted", "Feed Deleted"),
                            ("indicator_added", "Indicator Added"),
                            ("indicators_bulk_added", "Bulk Indicators Added"),
                            ("feed_updated", "Feed Updated"),
                            ("feed_error", "Feed Error"),
                            ("system_event", "System Event"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("feed", "Feed Activity"),
                            ("indicator", "Indicator Activity"),
                            ("system", "System Activity"),
                            ("user", "User Activity"),
                        ],
                        default="system",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "indicator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.indicator",
                    ),
                ),
                (
                    "threat_feed",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.threatfeed",
                    ),
                ),
            ],
            options={
                "verbose_name": "System Activity",
                "verbose_name_plural": "System Activities",
                "ordering": ["-created_at"],
            },
        ),
    ]
