# Generated by Django 4.2.10 on 2025-09-17 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_indicator_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ttpdata',
            unique_together={('mitre_technique_id', 'threat_feed')},
        ),
        migrations.AlterField(
            model_name='ttpdata',
            name='stix_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='ttpdata',
            unique_together={('stix_id', 'threat_feed'), ('mitre_technique_id', 'threat_feed')},
        ),
    ]
