# Generated by Django 4.2.24 on 2025-09-20 06:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0004_alter_ttpdata_unique_together_alter_ttpdata_stix_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="IndicatorSharingRelationship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "share_method",
                    models.CharField(
                        choices=[
                            ("taxii", "TAXII"),
                            ("api", "API"),
                            ("email", "Email"),
                        ],
                        default="taxii",
                        max_length=20,
                    ),
                ),
                (
                    "anonymization_level",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("minimal", "Minimal"),
                            ("partial", "Partial"),
                            ("full", "Full"),
                        ],
                        default="partial",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("shared_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "indicator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sharing_relationships",
                        to="core.indicator",
                    ),
                ),
                (
                    "shared_by_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_indicators",
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "db_table": "core_indicator_sharing_relationships",
                "ordering": ["-shared_at"],
                "unique_together": {("indicator", "target_organization")},
            },
        ),
    ]
