# Generated by Django 4.2.23 on 2025-08-09 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Whether this organization is active"
            ),
        ),
    ]
