# Generated by Django 4.2.10 on 2025-08-12 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_userinvitation_passwordresettoken'),
        ('core', '0006_delete_userprofile'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='trustrelationship',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='trustrelationship',
            name='source_organization',
        ),
        migrations.RemoveField(
            model_name='trustrelationship',
            name='target_organization',
        ),
        migrations.RemoveField(
            model_name='trustrelationship',
            name='trust_level',
        ),
        migrations.AlterField(
            model_name='collection',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_collections', to='user_management.organization'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publication_feeds', to='user_management.organization'),
        ),
        migrations.AlterField(
            model_name='identity',
            name='organization',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stix_identity', to='user_management.organization'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='organization',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_management.organization'),
        ),
        migrations.AlterField(
            model_name='networkmembership',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.organization'),
        ),
        migrations.AlterField(
            model_name='stixobject',
            name='source_organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stix_objects', to='user_management.organization'),
        ),
        migrations.AlterField(
            model_name='threatfeed',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_threat_feeds', to='user_management.organization'),
        ),
        migrations.AlterField(
            model_name='trustnetwork',
            name='members',
            field=models.ManyToManyField(related_name='trust_networks', through='core.NetworkMembership', to='user_management.organization'),
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
        migrations.DeleteModel(
            name='TrustRelationship',
        ),
    ]
