# Generated by Django 4.2.10 on 2025-09-24 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_add_asset_alert_models"),
    ]

    operations = [
        migrations.RunSQL(
            """
            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1 FROM information_schema.columns 
                    WHERE table_name = 'core_systemactivity' 
                    AND column_name = 'organization_id'
                ) THEN
                    ALTER TABLE core_systemactivity 
                    ADD COLUMN organization_id UUID REFERENCES core_organization(id) ON DELETE CASCADE;
                END IF;
            END $$;
            """,
            reverse_sql="ALTER TABLE core_systemactivity DROP COLUMN IF EXISTS organization_id;"
        ),
        migrations.RunSQL(
            "CREATE TABLE IF NOT EXISTS core_trustlog (id SERIAL PRIMARY KEY, action VARCHAR(50), source_organization_id UUID, target_organization_id UUID, details TEXT, created_at TIMESTAMP DEFAULT NOW());",
            reverse_sql="DROP TABLE IF EXISTS core_trustlog;"
        ),
    ]
