# Generated by Django 4.2.10 on 2025-09-24 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_add_asset_alert_models"),
    ]

    operations = [
        migrations.AddField(
            model_name='systemactivity',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.organization'),
        ),
        migrations.RunSQL(
            "CREATE TABLE IF NOT EXISTS core_trustlog (id SERIAL PRIMARY KEY, action VARCHAR(50), source_organization_id UUID, target_organization_id UUID, details TEXT, created_at TIMESTAMP DEFAULT NOW());",
            reverse_sql="DROP TABLE IF EXISTS core_trustlog;"
        ),
    ]
