# Generated by Django 4.2.10 on 2025-09-25 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_add_report_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='threatfeed',
            name='consumption_status',
            field=models.CharField(choices=[('idle', 'Idle'), ('running', 'Running'), ('paused', 'Paused'), ('stopping', 'Stopping'), ('error', 'Error')], default='idle', help_text='Current consumption status for pause/resume functionality', max_length=20),
        ),
        migrations.AddField(
            model_name='threatfeed',
            name='current_task_id',
            field=models.CharField(blank=True, help_text='Current Celery task ID for consumption tracking', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='threatfeed',
            name='pause_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Metadata for resuming consumption from paused state (e.g., last processed item, progress info)'),
        ),
        migrations.AddField(
            model_name='threatfeed',
            name='paused_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when consumption was paused', null=True),
        ),
    ]
