# Generated by Django 4.2.10 on 2025-09-27 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_threatfeed_consumption_status_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="userinvitation",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="userinvitation",
            name="accepted_by",
        ),
        migrations.RemoveField(
            model_name="userinvitation",
            name="inviter",
        ),
        migrations.RemoveField(
            model_name="userinvitation",
            name="organization",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="user",
        ),
        migrations.RemoveField(
            model_name="usersession",
            name="user",
        ),
        migrations.AlterField(
            model_name="threatfeed",
            name="consumption_status",
            field=models.CharField(
                choices=[
                    ("idle", "Idle"),
                    ("running", "Running"),
                    ("paused", "Paused"),
                    ("stopping", "Stopping"),
                    ("completed", "Completed"),
                    ("error", "Error"),
                ],
                default="idle",
                help_text="Current consumption status for pause/resume functionality",
                max_length=20,
            ),
        ),
        migrations.DeleteModel(
            name="TrustedDevice",
        ),
        migrations.DeleteModel(
            name="UserInvitation",
        ),
        migrations.DeleteModel(
            name="UserProfile",
        ),
        migrations.DeleteModel(
            name="UserSession",
        ),
    ]
