# Generated by Django 4.2.10 on 2025-09-27 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_threatfeed_consumption_status_completed"),
    ]

    operations = [
        migrations.AddField(
            model_name="threatfeed",
            name="last_consumed",
            field=models.DateTimeField(
                blank=True,
                help_text="Last time this feed was successfully consumed",
                null=True,
            ),
        ),
    ]
