# Generated by Django 4.2.10 on 2025-09-28 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0011_threatfeed_last_consumed'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_key', models.CharField(db_index=True, max_length=40)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.FloatField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('login_method', models.CharField(default='password', max_length=50)),
                ('api_calls_count', models.IntegerField(default=0)),
                ('endpoints_accessed', models.JSONField(default=list)),
                ('data_records_accessed', models.IntegerField(default=0)),
                ('incidents_created', models.IntegerField(default=0)),
                ('incidents_modified', models.IntegerField(default=0)),
                ('incidents_assigned', models.IntegerField(default=0)),
                ('threat_feeds_accessed', models.IntegerField(default=0)),
                ('exports_performed', models.IntegerField(default=0)),
                ('is_anomalous', models.BooleanField(default=False)),
                ('anomaly_score', models.FloatField(default=0.0)),
                ('anomaly_reasons', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavior_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Session',
                'verbose_name_plural': 'User Sessions',
                'db_table': 'user_session',
            },
        ),
        migrations.CreateModel(
            name='UserBehaviorBaseline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('avg_login_frequency_per_day', models.FloatField(default=0.0)),
                ('avg_session_duration_minutes', models.FloatField(default=0.0)),
                ('common_login_hours', models.JSONField(default=list)),
                ('common_login_days', models.JSONField(default=list)),
                ('avg_api_calls_per_session', models.FloatField(default=0.0)),
                ('common_accessed_endpoints', models.JSONField(default=list)),
                ('avg_data_access_volume', models.FloatField(default=0.0)),
                ('common_ip_ranges', models.JSONField(default=list)),
                ('common_user_agents', models.JSONField(default=list)),
                ('avg_incidents_created_per_week', models.FloatField(default=0.0)),
                ('avg_incidents_assigned_per_week', models.FloatField(default=0.0)),
                ('common_incident_categories', models.JSONField(default=list)),
                ('baseline_period_start', models.DateTimeField()),
                ('baseline_period_end', models.DateTimeField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('total_sessions_analyzed', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='behavior_baseline', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Behavior Baseline',
                'verbose_name_plural': 'User Behavior Baselines',
                'db_table': 'user_behavior_baseline',
            },
        ),
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('login', 'User Login'), ('logout', 'User Logout'), ('api_call', 'API Call'), ('data_access', 'Data Access'), ('incident_create', 'Incident Created'), ('incident_update', 'Incident Updated'), ('incident_assign', 'Incident Assigned'), ('incident_delete', 'Incident Deleted'), ('export_data', 'Data Export'), ('admin_action', 'Admin Action'), ('config_change', 'Configuration Change')], max_length=20)),
                ('endpoint', models.CharField(blank=True, max_length=200)),
                ('method', models.CharField(blank=True, max_length=10)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('request_data', models.JSONField(blank=True, default=dict)),
                ('response_status', models.IntegerField(blank=True, null=True)),
                ('resource_accessed', models.CharField(blank=True, max_length=200)),
                ('resource_count', models.IntegerField(default=1)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.usersession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Activity Log',
                'verbose_name_plural': 'User Activity Logs',
                'db_table': 'user_activity_log',
            },
        ),
        migrations.CreateModel(
            name='BehaviorAnomaly',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('anomaly_type', models.CharField(choices=[('login_frequency', 'Unusual Login Frequency'), ('login_time', 'Unusual Login Time'), ('login_location', 'Unusual Login Location'), ('session_duration', 'Unusual Session Duration'), ('api_usage', 'Unusual API Usage'), ('data_access', 'Unusual Data Access Volume'), ('privilege_escalation', 'Potential Privilege Escalation'), ('bulk_export', 'Bulk Data Export'), ('failed_authentication', 'Multiple Failed Authentications'), ('concurrent_sessions', 'Unusual Concurrent Sessions'), ('incident_manipulation', 'Unusual Incident Activity')], max_length=30)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('confidence_score', models.FloatField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('detection_method', models.CharField(max_length=100)),
                ('baseline_value', models.FloatField(blank=True, null=True)),
                ('observed_value', models.FloatField(blank=True, null=True)),
                ('deviation_percentage', models.FloatField(blank=True, null=True)),
                ('context_data', models.JSONField(default=dict)),
                ('related_events', models.JSONField(default=list)),
                ('is_investigated', models.BooleanField(default=False)),
                ('investigation_notes', models.TextField(blank=True)),
                ('investigated_at', models.DateTimeField(blank=True, null=True)),
                ('is_false_positive', models.BooleanField(default=False)),
                ('is_confirmed_threat', models.BooleanField(default=False)),
                ('resolution_notes', models.TextField(blank=True)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('investigated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investigated_anomalies', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.usersession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavior_anomalies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Behavior Anomaly',
                'verbose_name_plural': 'Behavior Anomalies',
                'db_table': 'behavior_anomaly',
            },
        ),
        migrations.CreateModel(
            name='BehaviorAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('immediate', 'Immediate Threat'), ('suspicious', 'Suspicious Activity'), ('policy_violation', 'Policy Violation'), ('data_exfiltration', 'Potential Data Exfiltration')], max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('recommended_actions', models.JSONField(default=list)),
                ('auto_actions_taken', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_behavior_alerts', to=settings.AUTH_USER_MODEL)),
                ('anomaly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.behavioranomaly')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavior_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Behavior Alert',
                'verbose_name_plural': 'Behavior Alerts',
                'db_table': 'behavior_alert',
            },
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['user', 'start_time'], name='user_sessio_user_id_6c80c6_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['ip_address', 'start_time'], name='user_sessio_ip_addr_73c72b_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['is_anomalous', 'anomaly_score'], name='user_sessio_is_anom_699997_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivitylog',
            index=models.Index(fields=['user', 'timestamp'], name='user_activi_user_id_3e368e_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivitylog',
            index=models.Index(fields=['action_type', 'timestamp'], name='user_activi_action__871490_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivitylog',
            index=models.Index(fields=['ip_address', 'timestamp'], name='user_activi_ip_addr_e662de_idx'),
        ),
        migrations.AddIndex(
            model_name='behavioranomaly',
            index=models.Index(fields=['user', 'detected_at'], name='behavior_an_user_id_f3f2d7_idx'),
        ),
        migrations.AddIndex(
            model_name='behavioranomaly',
            index=models.Index(fields=['anomaly_type', 'severity'], name='behavior_an_anomaly_60e570_idx'),
        ),
        migrations.AddIndex(
            model_name='behavioranomaly',
            index=models.Index(fields=['is_investigated', 'confidence_score'], name='behavior_an_is_inve_505abd_idx'),
        ),
        migrations.AddIndex(
            model_name='behavioralert',
            index=models.Index(fields=['user', 'created_at'], name='behavior_al_user_id_2b20ff_idx'),
        ),
        migrations.AddIndex(
            model_name='behavioralert',
            index=models.Index(fields=['alert_type', 'priority'], name='behavior_al_alert_t_acaa1f_idx'),
        ),
        migrations.AddIndex(
            model_name='behavioralert',
            index=models.Index(fields=['is_acknowledged', 'created_at'], name='behavior_al_is_ackn_5f255f_idx'),
        ),
    ]
