# Generated by Django 4.2.10 on 2025-10-15 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_usersession_userbehaviorbaseline_useractivitylog_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="indicator",
            index=models.Index(
                fields=["threat_feed", "-created_at"], name="indicator_feed_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="indicator",
            index=models.Index(
                fields=["type", "confidence"], name="indicator_type_conf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="indicator",
            index=models.Index(
                fields=["is_anonymized", "-last_seen"],
                name="indicator_anon_lastseen_idx",
            ),
        ),
    ]
