#!/bin/bash

# CRISP Platform Help Script
echo "🛡️  CRISP - Cyber Risk Information Sharing Platform"
echo "=================================================="
echo ""
echo "📖 Available Commands:"
echo ""

echo "🚀 SERVER MANAGEMENT:"
echo "  ./run_server.sh      - Start the Django development server"
echo "  ./stop_server.sh     - Stop all Django server processes"
echo "  ./check_status.sh    - Check platform status and health"
echo ""

echo "🧪 TESTING:"
echo "  ./run_tests.sh models       - Run quick model tests (28 tests)"
echo "  ./run_tests.sh all          - Run all comprehensive tests (675+ tests)"
echo "  ./run_tests.sh trust        - Run trust management tests"
echo "  ./run_tests.sh user         - Run user management tests"
echo "  ./run_tests.sh integration  - Run integration tests"
echo ""

echo "🔧 MANUAL COMMANDS:"
echo "  cd crisp && python3 manage.py runserver 0.0.0.0:8000  - Start server manually"
echo "  cd crisp && python3 manage.py test --keepdb           - Run tests manually"
echo "  cd crisp && python3 manage.py createsuperuser         - Create admin user"
echo "  cd crisp && python3 manage.py migrate                 - Apply database migrations"
echo "  cd crisp && python3 manage.py check                   - Check Django configuration"
echo ""

echo "🌐 ACCESS POINTS (when server is running):"
echo "  http://localhost:8000           - Main application"
echo "  http://localhost:8000/admin/    - Admin interface"
echo "  http://localhost:8000/api/v1/   - RESTful API endpoints"
echo ""

echo "📊 PLATFORM FEATURES:"
echo "  ✅ Trust Management - Organizations can establish trust relationships"
echo "  ✅ User Management - Role-based access control (Viewer, Publisher, Admin)"
echo "  ✅ Security Features - JWT auth, audit logging, rate limiting"
echo "  ✅ RESTful API - Comprehensive endpoints for all operations"
echo "  ✅ PostgreSQL Database - Production-ready data storage"
echo "  ✅ Comprehensive Testing - 675+ tests with 99%+ success rate"
echo ""

echo "🔐 USER ROLES:"
echo "  👁️  Viewer - View shared intelligence within trust relationships"
echo "  📤 Publisher - Share intelligence, manage users, create trust relationships"
echo "  👑 BlueVision Administrator - Full system access and monitoring"
echo ""

echo "🛠️  TROUBLESHOOTING:"
echo "  • Port in use: ./stop_server.sh then ./run_server.sh"
echo "  • Database issues: Check PostgreSQL with 'pg_isready'"
echo "  • Django errors: Run 'cd crisp && python3 manage.py check'"
echo "  • Test failures: Run './run_tests.sh models' for quick check"
echo ""

echo "📚 PROJECT STRUCTURE:"
echo "  core/trust/          - Trust management module"
echo "  core/user_management/ - User and organization management"
echo "  core/tests/          - Comprehensive test suite"
echo "  crisp/TrustManagement/ - Django project settings"
echo ""

echo "💡 QUICK START:"
echo "  1. ./check_status.sh  - Check system status"
echo "  2. ./run_server.sh    - Start the server"
echo "  3. ./run_tests.sh models - Verify functionality"
echo "  4. Visit http://localhost:8000 - Use the platform"
echo ""

echo "🆘 SUPPORT:"
echo "  • Check logs in crisp/logs/ for debugging"
echo "  • Run status check for system health"
echo "  • Review test results for functionality verification"
echo ""

echo "🏁 CRISP Platform Ready for Cyber Risk Information Sharing! 🛡️"