# Generated by Django 4.2.10 on 2025-08-11 10:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user_management", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("trust", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="trustrelationship",
            name="approved_by_source_user",
            field=models.ForeignKey(
                blank=True,
                help_text="User who approved on behalf of source organization",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="trust_approvals_as_source",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="trustrelationship",
            name="approved_by_target_user",
            field=models.ForeignKey(
                blank=True,
                help_text="User who approved on behalf of target organization",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="trust_approvals_as_target",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="trustrelationship",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this relationship",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_trust_relationships",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="trustrelationship",
            name="last_modified_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last modified this relationship",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="modified_trust_relationships",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="trustrelationship",
            name="revoked_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who revoked this relationship",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="revoked_trust_relationships",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="trustrelationship",
            name="source_organization",
            field=models.ForeignKey(
                help_text="Source organization in the trust relationship",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trust_relationships_as_source",
                to="user_management.organization",
            ),
        ),
        migrations.AddField(
            model_name="trustrelationship",
            name="target_organization",
            field=models.ForeignKey(
                help_text="Target organization in the trust relationship",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trust_relationships_as_target",
                to="user_management.organization",
            ),
        ),
        migrations.AddField(
            model_name="trustrelationship",
            name="trust_group",
            field=models.ForeignKey(
                blank=True,
                help_text="Trust group if this is a community relationship",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="group_relationships",
                to="trust.trustgroup",
            ),
        ),
        migrations.AddField(
            model_name="trustrelationship",
            name="trust_level",
            field=models.ForeignKey(
                help_text="Trust level for this relationship",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trust_relationships",
                to="trust.trustlevel",
            ),
        ),
        migrations.AddField(
            model_name="trustlog",
            name="source_organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organization that initiated the action",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="trust_logs_as_source",
                to="user_management.organization",
            ),
        ),
        migrations.AddField(
            model_name="trustlog",
            name="target_organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Target organization (if applicable)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="trust_logs_as_target",
                to="user_management.organization",
            ),
        ),
        migrations.AddField(
            model_name="trustlog",
            name="trust_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="trust_logs_as_user",
                to="trust.trustgroup",
            ),
        ),
        migrations.AddField(
            model_name="trustlog",
            name="trust_relationship",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="trust_logs",
                to="trust.trustrelationship",
            ),
        ),
        migrations.AddField(
            model_name="trustlog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="User who performed the action",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="performed_trust_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="trustlevel",
            index=models.Index(fields=["level"], name="trust_trust_level_2e1b62_idx"),
        ),
        migrations.AddIndex(
            model_name="trustlevel",
            index=models.Index(
                fields=["numerical_value"], name="trust_trust_numeric_22befe_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trustlevel",
            index=models.Index(
                fields=["is_active"], name="trust_trust_is_acti_70e94b_idx"
            ),
        ),
        migrations.AddField(
            model_name="trustgroupmembership",
            name="organization",
            field=models.ForeignKey(
                help_text="Organization that is a member of this trust group",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trust_group_memberships",
                to="user_management.organization",
            ),
        ),
        migrations.AddField(
            model_name="trustgroupmembership",
            name="trust_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="group_memberships",
                to="trust.trustgroup",
            ),
        ),
        migrations.AddField(
            model_name="trustgroup",
            name="default_trust_level",
            field=models.ForeignKey(
                help_text="Default trust level for group members",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="default_for_groups",
                to="trust.trustlevel",
            ),
        ),
        migrations.AddIndex(
            model_name="trustrelationship",
            index=models.Index(
                fields=["source_organization"], name="trust_trust_source__9eceb2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trustrelationship",
            index=models.Index(
                fields=["target_organization"], name="trust_trust_target__10f9a5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trustrelationship",
            index=models.Index(fields=["status"], name="trust_trust_status_e33fa5_idx"),
        ),
        migrations.AddIndex(
            model_name="trustrelationship",
            index=models.Index(
                fields=["trust_level"], name="trust_trust_trust_l_64cad0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trustrelationship",
            index=models.Index(
                fields=["is_active"], name="trust_trust_is_acti_f1a7fe_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trustrelationship",
            index=models.Index(
                fields=["valid_from"], name="trust_trust_valid_f_cbbc76_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trustrelationship",
            index=models.Index(
                fields=["valid_until"], name="trust_trust_valid_u_a07fc8_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="trustrelationship",
            unique_together={("source_organization", "target_organization")},
        ),
        migrations.AddIndex(
            model_name="trustlog",
            index=models.Index(
                fields=["action", "-timestamp"], name="trust_trust_action_2c2930_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trustlog",
            index=models.Index(
                fields=["source_organization", "-timestamp"],
                name="trust_trust_source__da2439_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="trustlog",
            index=models.Index(
                fields=["target_organization", "-timestamp"],
                name="trust_trust_target__84a07c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="trustlog",
            index=models.Index(
                fields=["user", "-timestamp"], name="trust_trust_user_id_448412_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trustlog",
            index=models.Index(
                fields=["success", "-timestamp"], name="trust_trust_success_06bf9e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trustgroupmembership",
            index=models.Index(
                fields=["organization"], name="trust_trust_organiz_45b49a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trustgroupmembership",
            index=models.Index(
                fields=["is_active"], name="trust_trust_is_acti_c77aa4_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="trustgroupmembership",
            unique_together={("trust_group", "organization")},
        ),
        migrations.AddIndex(
            model_name="trustgroup",
            index=models.Index(
                fields=["group_type"], name="trust_trust_group_t_848de0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trustgroup",
            index=models.Index(
                fields=["is_public"], name="trust_trust_is_publ_afce9a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trustgroup",
            index=models.Index(
                fields=["is_active"], name="trust_trust_is_acti_adc207_idx"
            ),
        ),
    ]
