# Generated by Django 4.2.10 on 2025-07-08 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("user_management", "0001_initial"),
        ("trust", "0002_update_for_user_management"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="trustgroupmembership",
            new_name="trust_trust_organiz_45b49a_idx",
            old_name="trust_trust_organiz_5c1aea_idx",
        ),
        migrations.RenameIndex(
            model_name="trustlog",
            new_name="trust_trust_source__da2439_idx",
            old_name="trust_trust_source__f0bd3f_idx",
        ),
        migrations.RenameIndex(
            model_name="trustlog",
            new_name="trust_trust_target__84a07c_idx",
            old_name="trust_trust_target__98d1b7_idx",
        ),
        migrations.RenameIndex(
            model_name="trustlog",
            new_name="trust_trust_user_id_448412_idx",
            old_name="trust_trust_user_6e5ed3_idx",
        ),
        migrations.RenameIndex(
            model_name="trustrelationship",
            new_name="trust_trust_source__9eceb2_idx",
            old_name="trust_trust_source__9d509b_idx",
        ),
        migrations.RenameIndex(
            model_name="trustrelationship",
            new_name="trust_trust_target__10f9a5_idx",
            old_name="trust_trust_target__270379_idx",
        ),
        migrations.AddField(
            model_name="trustrelationship",
            name="source_approval_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="trustrelationship",
            name="target_approval_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="trustgroupmembership",
            name="organization",
            field=models.ForeignKey(
                help_text="Organization that is a member of this trust group",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trust_group_memberships",
                to="user_management.organization",
            ),
        ),
        migrations.AlterField(
            model_name="trustlevel",
            name="level",
            field=models.CharField(
                choices=[
                    ("public", "Public Trust"),
                    ("trusted", "Trusted Trust"),
                    ("restricted", "Restricted Trust"),
                ],
                help_text="Standard trust level classification",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="trustlog",
            name="trust_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="trust_logs_as_user",
                to="trust.trustgroup",
            ),
        ),
        migrations.AlterField(
            model_name="trustlog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="User who performed the action",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="performed_trust_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="trustrelationship",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this relationship",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_trust_relationships",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="trustrelationship",
            name="source_organization",
            field=models.ForeignKey(
                help_text="Source organization in the trust relationship",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trust_relationships_as_source",
                to="user_management.organization",
            ),
        ),
        migrations.AlterField(
            model_name="trustrelationship",
            name="target_organization",
            field=models.ForeignKey(
                help_text="Target organization in the trust relationship",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trust_relationships_as_target",
                to="user_management.organization",
            ),
        ),
    ]
