# Generated by Django 5.2.3 on 2025-06-21 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crisp_threat_intel', '0002_rename_crisp_threa_collect_0b6e56_idx_crisp_threa_collect_2ce644_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='stix_objects',
            field=models.ManyToManyField(related_name='collections', through='crisp_threat_intel.CollectionObject', through_fields=('collection', 'stix_object'), to='crisp_threat_intel.stixobject'),
        ),
    ]
