# Generated by Django 4.2.10 on 2025-07-03 12:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("crisp_threat_intel", "0003_alter_collection_stix_objects"),
    ]

    operations = [
        migrations.CreateModel(
            name="NetworkMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "membership_level",
                    models.CharField(
                        choices=[
                            ("full", "Full Member"),
                            ("associate", "Associate Member"),
                            ("observer", "Observer"),
                        ],
                        max_length=50,
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="collection",
            name="default_anonymization",
        ),
        migrations.AddField(
            model_name="collection",
            name="default_anonymization_level",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("low", "Low"),
                    ("medium", "Medium"),
                    ("high", "High"),
                    ("full", "Full"),
                ],
                default="medium",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="organization_type",
            field=models.CharField(
                choices=[
                    ("university", "University"),
                    ("college", "College"),
                    ("school", "School"),
                    ("government", "Government"),
                    ("commercial", "Commercial"),
                    ("research", "Research Institution"),
                    ("ngo", "Non-Governmental Organization"),
                ],
                default="university",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="TrustNetwork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("default_trust_level", models.FloatField(default=0.6)),
                (
                    "default_anonymization_level",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("full", "Full"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "members",
                    models.ManyToManyField(
                        related_name="trust_networks",
                        through="crisp_threat_intel.NetworkMembership",
                        to="crisp_threat_intel.organization",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="networkmembership",
            name="network",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="crisp_threat_intel.trustnetwork",
            ),
        ),
        migrations.AddField(
            model_name="networkmembership",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="crisp_threat_intel.organization",
            ),
        ),
        migrations.CreateModel(
            name="TrustRelationship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "trust_level",
                    models.FloatField(
                        choices=[
                            (1.0, "Full Trust"),
                            (0.8, "High Trust"),
                            (0.6, "Medium Trust"),
                            (0.4, "Low Trust"),
                            (0.2, "Minimal Trust"),
                            (0.0, "No Trust"),
                        ],
                        default=0.5,
                    ),
                ),
                (
                    "anonymization_override",
                    models.CharField(
                        blank=True,
                        help_text="Override anonymization level for this relationship",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trust_given",
                        to="crisp_threat_intel.organization",
                    ),
                ),
                (
                    "target_org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trust_received",
                        to="crisp_threat_intel.organization",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["source_org", "target_org"],
                        name="crisp_threa_source__2a7fd2_idx",
                    ),
                    models.Index(
                        fields=["trust_level"], name="crisp_threa_trust_l_34fcd0_idx"
                    ),
                ],
                "unique_together": {("source_org", "target_org")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="networkmembership",
            unique_together={("organization", "network")},
        ),
    ]
