# Generated by Django 4.2.10 on 2025-07-03 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crisp_threat_intel", "0004_networkmembership_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stixobject",
            name="anonymization_trust_level",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="stixobject",
            name="original_data",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
