# Generated by Django 4.2.10 on 2025-07-03 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crisp_threat_intel", "0005_stixobject_anonymization_trust_level_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='domain',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
