services:
  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: crisp
      POSTGRES_USER: crisp_user
      POSTGRES_PASSWORD: crisp_password
      POSTGRES_HOST_AUTH_METHOD: md5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    mem_limit: 512m
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U crisp_user -d crisp"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 120s
    networks:
      - crisp-network

  # Redis Cache
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - crisp-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Django Backend
  backend:
    build:
      context: .
      target: backend
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - SECRET_KEY=(2-yp3pr5_y^w1w9@3)k#&gib*+jm*@)8$$b6oitfi!(094l+e4
      - TRUST_MANAGEMENT_SECRET_KEY=your-trust-management-secret-key
      - OTX_API_KEY=e3c65c53199dbab88329fa84e9336926e94fcb3777beb5a8f7647229b61efa26
      - VIRUSTOTAL_API_KEY=ea04902bb47510876f6f3cb60ca971a6085cd0f92c8f8212ed4c19ff81a7d916
      - DB_NAME=crisp
      - DB_USER=crisp_user
      - DB_PASSWORD=crisp_password
      - DB_HOST=db
      - DB_PORT=5432
      - REDIS_URL=redis://redis:6379/0
      - ALLOWED_HOSTS=localhost,127.0.0.1,backend,frontend
      - POPULATE_TEST_DATA=true
      - EMAIL_BACKEND=django.core.mail.backends.smtp.EmailBackend
      - EMAIL_HOST=smtp.gmail.com
      - EMAIL_PORT=587
      - EMAIL_USE_TLS=true
      - EMAIL_HOST_USER=cos332practical6@gmail.com
      - EMAIL_HOST_PASSWORD=glrk anea ypnl hruw
      - DEFAULT_FROM_EMAIL=cos332practical6@gmail.com
    volumes:
      - ./logs:/app/logs
      - ./media:/app/media
      - ./core:/app/core
      - ./settings:/app/settings
      - ./manage.py:/app/manage.py
      - ./requirements.txt:/app/requirements.txt
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - crisp-network
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py setup_base_users &&
             if [ \"$$POPULATE_TEST_DATA\" = \"true\" ]; then
               echo 'Populating test data...' &&
               python manage.py populate_database --no-input;
             fi &&
             echo 'Cleaning up invalid feeds...' &&
             python manage.py cleanup_feeds --force &&
             echo 'Setting up VirusTotal feed...' &&
             python manage.py setup_virustotal_feed --with-samples &&
             python manage.py collectstatic --noinput &&
             python manage.py runserver 0.0.0.0:8000"

  # Vite Frontend
  frontend:
    build:
      context: .
      target: frontend-dev
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8000
    volumes:
      - ./frontend/crisp-react:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - crisp-network

  # Testing Backend with Large Dataset
  backend-test:
    build:
      context: .
      target: backend
    ports:
      - "8001:8000"
    environment:
      - DEBUG=True
      - SECRET_KEY=(2-yp3pr5_y^w1w9@3)k#&gib*+jm*@)8-b6oitfi!(094l+e4-test
      - TRUST_MANAGEMENT_SECRET_KEY=your-trust-management-secret-key
      - OTX_API_KEY=e3c65c53199dbab88329fa84e9336926e94fcb3777beb5a8f7647229b61efa26
      - VIRUSTOTAL_API_KEY=ea04902bb47510876f6f3cb60ca971a6085cd0f92c8f8212ed4c19ff81a7d916
      - DB_NAME=crisp_test
      - DB_USER=crisp_user
      - DB_PASSWORD=crisp_password
      - DB_HOST=db-test
      - DB_PORT=5432
      - REDIS_URL=redis://redis-test:6379/0
      - ALLOWED_HOSTS=localhost,127.0.0.1,backend-test,frontend-test
      - POPULATE_TEST_DATA=true
      - EMAIL_BACKEND=django.core.mail.backends.smtp.EmailBackend
      - EMAIL_HOST=smtp.gmail.com
      - EMAIL_PORT=587
      - EMAIL_USE_TLS=true
      - EMAIL_HOST_USER=cos332practical6@gmail.com
      - EMAIL_HOST_PASSWORD=glrk anea ypnl hruw
      - DEFAULT_FROM_EMAIL=cos332practical6@gmail.com
    volumes:
      - ./logs:/app/logs
      - ./media:/app/media
      - ./core:/app/core
      - ./settings:/app/settings
      - ./manage.py:/app/manage.py
      - ./requirements.txt:/app/requirements.txt
    depends_on:
      db-test:
        condition: service_healthy
      redis-test:
        condition: service_healthy
    networks:
      - crisp-test-network
    command: >
      sh -c "until pg_isready -h db-test -p 5432; do echo 'Waiting for test db...'; sleep 2; done &&
             python manage.py migrate &&
             python manage.py setup_base_users &&
             if [ \"$$POPULATE_TEST_DATA\" = \"true\" ]; then
               echo 'Populating test data...' &&
               python manage.py populate_database --no-input &&
               echo 'Populating TTP data...' &&
               python manage.py populate_ttp_data --count 100;
             fi &&
             python manage.py collectstatic --noinput &&
             python manage.py runserver 0.0.0.0:8000"
    profiles: ["test"]

  # Testing PostgreSQL Database
  db-test:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: crisp_test
      POSTGRES_USER: crisp_user
      POSTGRES_PASSWORD: crisp_password
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U crisp_user -d crisp_test"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 30s
    networks:
      - crisp-test-network
    profiles: ["test"]

  # Testing Redis Cache
  redis-test:
    image: redis:7-alpine
    ports:
      - "6380:6379"
    volumes:
      - redis_test_data:/data
    networks:
      - crisp-test-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    profiles: ["test"]

  # Testing Vite Frontend
  frontend-test:
    build:
      context: .
      target: frontend-dev
    ports:
      - "5174:5173"
    environment:
      - VITE_API_URL=http://localhost:8001
    volumes:
      - ./frontend/crisp-react:/app
      - /app/node_modules
    depends_on:
      - backend-test
    networks:
      - crisp-test-network
    profiles: ["test"]

volumes:
  postgres_data:
  redis_data:
  postgres_test_data:
  redis_test_data:

networks:
  crisp-network:
    driver: bridge
  crisp-test-network:
    driver: bridge