-- Fix PostgreSQL permissions for crisp_user
GRANT ALL PRIVILEGES ON SCHEMA public TO crisp_user;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO crisp_user;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO crisp_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO crisp_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON SEQUENCES TO crisp_user;