services:
  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: crisp_production
      POSTGRES_USER: crisp_production
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: md5
    command: [
      "postgres",
      "-c", "fsync=on",
      "-c", "synchronous_commit=on",
      "-c", "full_page_writes=on",
      "-c", "max_wal_size=1GB",
      "-c", "checkpoint_completion_target=0.9",
      "-c", "wal_buffers=16MB",
      "-c", "shared_buffers=256MB",
      "-c", "max_connections=100",
      "-c", "log_statement=mod"
    ]
    volumes:
      - postgres_production_data:/var/lib/postgresql/data
      - ./backups:/backups
    ports:
      - "5432:5432"
    mem_limit: 512m
    mem_reservation: 256m
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U crisp_production -d crisp_production"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - crisp-production

  # Redis Cache
  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes --maxmemory 128mb --maxmemory-policy allkeys-lru
    volumes:
      - redis_production_data:/data
    ports:
      - "6379:6379"
    mem_limit: 128m
    mem_reservation: 64m
    restart: unless-stopped
    networks:
      - crisp-production
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 5s
      retries: 3

  # CRISP Production Application
  app:
    image: datadefenders/crisp:${CRISP_IMAGE_TAG:-latest}
    command: sh -c "python manage.py migrate && python manage.py create_default_admin && python manage.py collectstatic --noinput && gunicorn --bind 0.0.0.0:8000 --workers 1 --threads 2 --timeout 600 --graceful-timeout 120 --max-requests 500 --max-requests-jitter 50 --worker-class sync settings.wsgi:application"
    environment:
      - DEBUG=False
      - SECRET_KEY=${SECRET_KEY}
      - DB_NAME=crisp_production
      - DB_USER=crisp_production
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=db
      - DB_PORT=5432
      - REDIS_URL=redis://redis:6379/0
      - ALLOWED_HOSTS=data-defenders.co.za,www.data-defenders.co.za,localhost,app,wpad.up.ac.za,206.81.22.242
      - CSRF_TRUSTED_ORIGINS=https://data-defenders.co.za,https://www.data-defenders.co.za
      - POPULATE_TEST_DATA=false
      - CORS_ALLOWED_ORIGINS=http://localhost,http://localhost:3000,http://localhost:5173,http://localhost:5174,http://localhost:5175
    volumes:
      - ./logs:/app/logs
      - ./media:/app/media
      - ./backups:/app/backups
      - static_volume:/app/staticfiles
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped
    mem_limit: 1200m
    mem_reservation: 800m
    networks:
      - crisp-production
    # Healthcheck disabled for low-memory server - check manually with: docker logs root-app-1
    # healthcheck:
    #   test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8000/health/ || exit 1"]
    #   interval: 60s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 180s

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx-production.conf:/etc/nginx/nginx.conf:ro
      - static_volume:/usr/share/nginx/html/static:ro
    depends_on:
      - app
    restart: unless-stopped
    mem_limit: 64m
    networks:
      - crisp-production

volumes:
  postgres_production_data:
    driver: local
  redis_production_data:
    driver: local
  static_volume:
    driver: local

networks:
  crisp-production:
    driver: bridge