# Generated by Django 4.2.10 on 2025-07-23 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "user_management",
            "0002_alter_customuser_managers_alter_customuser_metadata_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="organization_type",
            field=models.CharField(
                choices=[
                    ("educational", "Educational"),
                    ("government", "Government"),
                    ("private", "Private"),
                ],
                default="educational",
                help_text="Type of organization (educational, government, private)",
                max_length=100,
            ),
        ),
    ]
