# Generated by Django 4.2.10 on 2025-06-21 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crisp_threat_intel', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='collectionobject',
            new_name='crisp_threa_collect_2ce644_idx',
            old_name='crisp_threa_collect_0b6e56_idx',
        ),
        migrations.RenameIndex(
            model_name='collectionobject',
            new_name='crisp_threa_date_ad_30082a_idx',
            old_name='crisp_threa_date_ad_63f52a_idx',
        ),
        migrations.RenameIndex(
            model_name='stixobject',
            new_name='crisp_threa_stix_ty_8ef1e1_idx',
            old_name='crisp_threa_stix_ty_7e6a86_idx',
        ),
        migrations.RenameIndex(
            model_name='stixobject',
            new_name='crisp_threa_created_3265bf_idx',
            old_name='crisp_threa_created_bb39d1_idx',
        ),
        migrations.RenameIndex(
            model_name='stixobject',
            new_name='crisp_threa_modifie_b650f7_idx',
            old_name='crisp_threa_modifie_b0397b_idx',
        ),
        migrations.RenameIndex(
            model_name='stixobject',
            new_name='crisp_threa_created_cc0d5b_idx',
            old_name='crisp_threa_created_e79f50_idx',
        ),
        migrations.RenameIndex(
            model_name='stixobject',
            new_name='crisp_threa_anonymi_da923f_idx',
            old_name='crisp_threa_anonymi_0a2b6b_idx',
        ),
    ]
