# Generated by Django 4.2.10 on 2025-07-07 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trustlevel',
            name='level',
        ),
        migrations.AlterField(
            model_name='trustlevel',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='trustlevel',
            name='numerical_value',
            field=models.IntegerField(default=50, unique=True),
        ),
    ]
