# Generated by Django 5.2.4 on 2025-07-07 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_trustlevel_level_alter_trustlevel_name_and_more'),
    ]

    operations = [
    ]
