# Generated by Django 4.2.21 on 2025-07-29 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_feed_created_by_feed_name_feed_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('feed_added', 'Feed Added'), ('feed_consumed', 'Feed Consumed'), ('indicator_added', 'Indicator Added'), ('indicators_bulk_added', 'Bulk Indicators Added'), ('feed_updated', 'Feed Updated'), ('feed_error', 'Feed Error'), ('system_event', 'System Event')], max_length=50)),
                ('category', models.CharField(choices=[('feed', 'Feed Activity'), ('indicator', 'Indicator Activity'), ('system', 'System Activity'), ('user', 'User Activity')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('indicator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.indicator')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.organization')),
                ('threat_feed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.threatfeed')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'system_activities',
                'ordering': ['-created_at'],
            },
        ),
    ]
