# Generated by Django 4.2.21 on 2025-08-10 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_system_activity_model'),
        ('core', '0005_add_ttp_filter_indexes'),
    ]

    operations = [
    ]
