# Generated by Django 4.2.21 on 2025-08-11 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_merge_20250810_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='systemactivity',
            name='activity_type',
            field=models.CharField(choices=[('feed_added', 'Feed Added'), ('feed_consumed', 'Feed Consumed'), ('feed_deleted', 'Feed Deleted'), ('indicator_added', 'Indicator Added'), ('indicators_bulk_added', 'Bulk Indicators Added'), ('feed_updated', 'Feed Updated'), ('feed_error', 'Feed Error'), ('system_event', 'System Event')], max_length=50),
        ),
    ]
