# Generated by Django 4.2.10 on 2025-07-23 19:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("user_management", "0003_alter_organization_organization_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email_type",
                    models.CharField(
                        choices=[
                            ("threat_alert", "Threat Alert"),
                            ("feed_notification", "Feed Notification"),
                            ("test_email", "Test Email"),
                            ("system_notification", "System Notification"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "recipient_emails",
                    models.JSONField(help_text="List of recipient email addresses"),
                ),
                ("sender_email", models.EmailField(max_length=255)),
                ("subject", models.CharField(max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                            ("pending", "Pending"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("sent_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("alert_id", models.CharField(blank=True, max_length=100, null=True)),
                ("priority", models.CharField(blank=True, max_length=20, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("retry_count", models.IntegerField(default=0)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_emails",
                        to="user_management.organization",
                    ),
                ),
                (
                    "sent_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_emails",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "crisp_email_logs",
                "ordering": ["-sent_at"],
                "indexes": [
                    models.Index(
                        fields=["email_type", "sent_at"],
                        name="crisp_email_email_t_847fd2_idx",
                    ),
                    models.Index(
                        fields=["status", "sent_at"],
                        name="crisp_email_status_22e160_idx",
                    ),
                    models.Index(
                        fields=["organization", "sent_at"],
                        name="crisp_email_organiz_a3355c_idx",
                    ),
                ],
            },
        ),
    ]
