# Generated by Django 4.2.10 on 2025-08-12 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial_ut'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailLog',
        ),
    ]
