# Generated by Django 4.2.10 on 2025-07-08 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user_management", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="customuser",
            managers=[],
        ),
        migrations.AlterField(
            model_name="customuser",
            name="metadata",
            field=models.JSONField(
                blank=True, default=dict, help_text="Additional user metadata"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users",
                to="user_management.organization",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="preferences",
            field=models.JSONField(
                blank=True, default=dict, help_text="User preferences and settings"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="trusted_devices",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of trusted device fingerprints",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="trust_metadata",
            field=models.JSONField(default=dict),
        ),
    ]
