# Generated by Django 4.2.23 on 2025-06-24 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TrustManagement", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trustlog",
            name="source_organization",
            field=models.CharField(
                blank=True,
                help_text="Organization that initiated the action",
                max_length=255,
                null=True,
            ),
        ),
    ]
