# Generated by Django 4.2.21 on 2025-05-27 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0003_organization_threatfeed_alter_crispuser_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crispuser',
            name='last_login_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
