# Generated by Django 4.2.10 on 2025-05-27 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_organization_contact_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feed',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='feed',
            name='last_published',
        ),
        migrations.AddField(
            model_name='collection',
            name='stix_objects',
            field=models.ManyToManyField(related_name='collections', through='core.CollectionObject', to='core.stixobject'),
        ),
        migrations.AddField(
            model_name='feed',
            name='next_publish_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feed',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('error', 'Error')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='feed',
            name='update_interval',
            field=models.IntegerField(default=3600),
        ),
    ]
