# Generated by Django 4.2.21 on 2025-05-27 09:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crispuser',
            name='failed_login_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='crispuser',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='crispuser',
            name='job_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='crispuser',
            name='last_password_change',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crispuser',
            name='organization',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crispuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='crispuser',
            name='require_password_change',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='crispuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('analyst', 'Security Analyst'), ('user', 'Standard User'), ('guest', 'Guest')], default='analyst', max_length=100),
        ),
    ]
