# Generated by Django 4.2.23 on 2025-07-04 12:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TrustGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField()),
                (
                    "group_type",
                    models.CharField(
                        choices=[
                            ("sector", "Sector-based"),
                            ("region", "Region-based"),
                            ("community", "Community"),
                            ("custom", "Custom"),
                        ],
                        default="community",
                        max_length=20,
                    ),
                ),
                ("is_public", models.BooleanField(default=True)),
                ("requires_approval", models.BooleanField(default=False)),
                ("administrators", models.JSONField(default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("created_by", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Trust Group",
                "verbose_name_plural": "Trust Groups",
                "db_table": "trust_groups",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TrustLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("trusted", "Trusted"),
                            ("restricted", "Restricted"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "numerical_value",
                    models.IntegerField(
                        help_text="Numerical value (0-100) for comparison"
                    ),
                ),
                ("description", models.TextField()),
                (
                    "default_anonymization_level",
                    models.CharField(
                        choices=[
                            ("full", "Full Anonymization"),
                            ("partial", "Partial Anonymization"),
                            ("minimal", "Minimal Anonymization"),
                        ],
                        default="full",
                        max_length=20,
                    ),
                ),
                (
                    "default_access_level",
                    models.CharField(
                        choices=[
                            ("read", "Read Only"),
                            ("contribute", "Contribute"),
                            ("admin", "Administrative"),
                        ],
                        default="read",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_system_default", models.BooleanField(default=False)),
                ("created_by", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Trust Level",
                "verbose_name_plural": "Trust Levels",
                "db_table": "trust_levels",
                "ordering": ["numerical_value"],
            },
        ),
        migrations.CreateModel(
            name="TrustRelationship",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source_organization",
                    models.UUIDField(help_text="UUID of source organization"),
                ),
                (
                    "target_organization",
                    models.UUIDField(help_text="UUID of target organization"),
                ),
                (
                    "relationship_type",
                    models.CharField(
                        choices=[
                            ("bilateral", "Bilateral"),
                            ("community", "Community"),
                            ("hierarchical", "Hierarchical"),
                            ("federation", "Federation"),
                        ],
                        default="bilateral",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("active", "Active"),
                            ("suspended", "Suspended"),
                            ("revoked", "Revoked"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("valid_from", models.DateTimeField(auto_now_add=True)),
                ("valid_until", models.DateTimeField(blank=True, null=True)),
                ("approved_by_source", models.BooleanField(default=False)),
                ("approved_by_target", models.BooleanField(default=False)),
                ("created_by", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_modified_by", models.CharField(max_length=100)),
                ("last_modified_at", models.DateTimeField(auto_now=True)),
                (
                    "trust_level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="trust_management.trustlevel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Trust Relationship",
                "verbose_name_plural": "Trust Relationships",
                "db_table": "trust_relationships",
                "ordering": ["-created_at"],
                "unique_together": {("source_organization", "target_organization")},
            },
        ),
        migrations.CreateModel(
            name="TrustLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("relationship_created", "Relationship Created"),
                            ("relationship_approved", "Relationship Approved"),
                            ("relationship_denied", "Relationship Denied"),
                            ("relationship_revoked", "Relationship Revoked"),
                            ("relationship_suspended", "Relationship Suspended"),
                            ("group_created", "Group Created"),
                            ("group_joined", "Group Joined"),
                            ("group_left", "Group Left"),
                            ("access_granted", "Access Granted"),
                            ("access_denied", "Access Denied"),
                            ("trust_level_changed", "Trust Level Changed"),
                        ],
                        max_length=50,
                    ),
                ),
                ("source_organization", models.UUIDField(blank=True, null=True)),
                ("target_organization", models.UUIDField(blank=True, null=True)),
                ("user", models.CharField(max_length=100)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("success", models.BooleanField(default=True)),
                ("details", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "trust_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="trust_management.trustgroup",
                    ),
                ),
                (
                    "trust_relationship",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="trust_management.trustrelationship",
                    ),
                ),
            ],
            options={
                "verbose_name": "Trust Log",
                "verbose_name_plural": "Trust Logs",
                "db_table": "trust_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="trustgroup",
            name="default_trust_level",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="trust_management.trustlevel",
            ),
        ),
        migrations.CreateModel(
            name="TrustGroupMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "organization",
                    models.UUIDField(help_text="UUID of member organization"),
                ),
                (
                    "membership_type",
                    models.CharField(
                        choices=[
                            ("member", "Member"),
                            ("administrator", "Administrator"),
                            ("moderator", "Moderator"),
                        ],
                        default="member",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("left_at", models.DateTimeField(blank=True, null=True)),
                (
                    "invited_by",
                    models.UUIDField(
                        blank=True, help_text="UUID of inviting organization", null=True
                    ),
                ),
                (
                    "approved_by",
                    models.UUIDField(
                        blank=True,
                        help_text="UUID of approving organization",
                        null=True,
                    ),
                ),
                (
                    "trust_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="trust_management.trustgroup",
                    ),
                ),
            ],
            options={
                "verbose_name": "Trust Group Membership",
                "verbose_name_plural": "Trust Group Memberships",
                "db_table": "trust_group_memberships",
                "ordering": ["-joined_at"],
                "unique_together": {("trust_group", "organization")},
            },
        ),
    ]
