# Generated by Django 4.2.10 on 2025-05-27 09:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrustGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('default_trust_level_name', models.CharField(choices=[('none', 'None'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20)),
                ('default_trust_level', models.FloatField(default=0.5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrustRelationship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trust_level_name', models.CharField(choices=[('none', 'None'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20)),
                ('trust_level', models.FloatField(default=0.5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('anonymization_strategy', models.CharField(default='partial', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('source_organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trusts', to='core.organization')),
                ('target_organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trusted_by', to='core.organization')),
            ],
            options={
                'indexes': [models.Index(fields=['source_organization', 'target_organization'], name='trust_trust_source__a1be6e_idx'), models.Index(fields=['trust_level'], name='trust_trust_trust_l_df20e0_idx')],
                'unique_together': {('source_organization', 'target_organization')},
            },
        ),
        migrations.CreateModel(
            name='TrustGroupMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trust_group_memberships', to='core.organization')),
                ('trust_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='trust.trustgroup')),
            ],
            options={
                'unique_together': {('trust_group', 'organization')},
            },
        ),
    ]
