# Generated by Django 4.2.10 on 2025-10-15 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("soc", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="socincident",
            index=models.Index(
                fields=["organization", "-created_at"], name="soc_inc_org_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="socincident",
            index=models.Index(
                fields=["organization", "status", "-created_at"],
                name="soc_inc_org_status_created_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="socincident",
            index=models.Index(
                fields=["category", "severity"], name="soc_inc_cat_sev_idx"
            ),
        ),
    ]
