# Generated by Django 5.2.4 on 2025-07-07 15:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20250707_1547'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feed',
            name='name',
            field=models.CharField(default='default', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feed',
            name='status',
            field=models.CharField(default='default', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trustlevel',
            name='level',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='collection',
            name='stix_objects',
            field=models.ManyToManyField(related_name='collections', through='core.CollectionObject', through_fields=('collection', 'stix_object'), to='core.stixobject'),
        ),
    ]
