# Generated by Django 4.2.10 on 2025-05-27 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action_type', models.CharField(choices=[('discovery', 'Discovery'), ('api_root', 'API Root'), ('list_collections', 'List Collections'), ('get_collection', 'Get Collection'), ('get_collection_objects', 'Get Collection Objects'), ('add_collection_objects', 'Add Collection Objects'), ('get_object', 'Get Object'), ('get_manifest', 'Get Manifest'), ('create_stix_object', 'Create STIX Object'), ('update_stix_object', 'Update STIX Object'), ('delete_stix_object', 'Delete STIX Object'), ('anonymize_object', 'Anonymize Object'), ('create_collection', 'Create Collection'), ('update_collection', 'Update Collection'), ('delete_collection', 'Delete Collection'), ('create_trust_relationship', 'Create Trust Relationship'), ('update_trust_relationship', 'Update Trust Relationship'), ('delete_trust_relationship', 'Delete Trust Relationship'), ('create_feed', 'Create Feed'), ('update_feed', 'Update Feed'), ('delete_feed', 'Delete Feed'), ('publish_feed', 'Publish Feed'), ('user_login', 'User Login'), ('user_logout', 'User Logout'), ('password_change', 'Password Change')], max_length=50)),
                ('object_id', models.CharField(blank=True, max_length=255, null=True)),
                ('details', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='core.organization')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SharingActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('stix_object_id', models.CharField(max_length=255)),
                ('stix_object_type', models.CharField(max_length=50)),
                ('collection_id', models.UUIDField()),
                ('anonymization_applied', models.BooleanField(default=False)),
                ('anonymization_strategy', models.CharField(blank=True, max_length=50, null=True)),
                ('trust_level', models.FloatField(blank=True, null=True)),
                ('audit_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sharing_details', to='audit.auditlog')),
                ('source_organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_from', to='core.organization')),
                ('target_organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_to', to='core.organization')),
            ],
            options={
                'indexes': [models.Index(fields=['timestamp'], name='audit_shari_timesta_ad56c3_idx'), models.Index(fields=['source_organization'], name='audit_shari_source__e84a73_idx'), models.Index(fields=['target_organization'], name='audit_shari_target__8ba32e_idx'), models.Index(fields=['stix_object_id'], name='audit_shari_stix_ob_ce64b2_idx'), models.Index(fields=['stix_object_type'], name='audit_shari_stix_ob_bc99c5_idx'), models.Index(fields=['collection_id'], name='audit_shari_collect_02061a_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['timestamp'], name='audit_audit_timesta_19e18a_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user'], name='audit_audit_user_id_292c79_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['organization'], name='audit_audit_organiz_b2fceb_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action_type'], name='audit_audit_action__dd3a3c_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['object_id'], name='audit_audit_object__9f698d_idx'),
        ),
    ]
