# Generated by Django 4.2.21 on 2025-05-27 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0004_crispuser_last_login_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='crispuser',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='crispuser',
            name='job_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='crispuser',
            name='last_password_change',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
